version: 1
root:
  level: DEBUG #DEBUG INFO WARNING ERROR CRITICAL
  handlers: [console]
loggers:
  scenario:
    level: DEBUG
    propagate: true
    handlers: []
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: std
    stream: ext://sys.stdout
formatters:
  std:
    format: "[%(asctime)s]|%(levelname)s|%(name)s|\"%(message)s\" by %(module)s.%(funcName)s:%(lineno)d on %(threadName)s "
incremental: false
disable_existing_loggers: true